version: '2'
services:
  3dmapweb:
    image: docker.alexandra.dk/3dmapweb:latest
    ports:
     - "80:80"
    restart: always
    depends_on:
     - 3dmapcityintegration
     - 3dmapservice
    logging:
      driver: json-file
      options:
         max-size: "1g"
         max-file: "5"

  3dmapcityintegration:
    image: docker.alexandra.dk/3dmapcityintegration:latest
    ports:
     - "8001:8001"
    restart: always
    logging:
      driver: json-file
      options:
         max-size: "1g"
         max-file: "5"
  3dmapatmosphereservice:
    image: docker.alexandra.dk/3dmapatmosphereservice:latest
    ports:
     - "8002:8002"
    restart: always
    logging:
      driver: json-file
      options:
         max-size: "1g"
         max-file: "5"
  3dmapcontrolservice:
    image: docker.alexandra.dk/3dmapcontrolservice:latest
    ports:
     - "8003:8003"
    restart: always
    logging:
      driver: json-file
      options:
         max-size: "1g"
         max-file: "5"

